version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "parse-threat-report"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-14dw0ywo31qp5"
s3_prefix = "parse-threat-report"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
